### ISSUE TITLE
Дизайн

### ISSUE THREAD

**Issue by Dandelianel** [op-onai/op-onai-platform#3]
1. Точки не везде проставлены.
2. Первая страница выглядит пустой - может добавить шапку?
3. Лого и Войти можно чуть крупнее сделать
4. Немного копирайтинга во второй странице:

Кратно повышАЙТЕ вашу мотивацию и успеваемость.
Разрабатывайте проекты с менторами, которые станут вашими Проект-Менеджерами.
Для полной эффективности _обучение_ требует практики и сообщества.

5. Ссылку "Подробнее" можно опустить чуть ниже и сделать более отличительной от других ссылок.
6. Во многих других страницах текст в блоках выравнен по левому краю. Вторая страница с серединным выравниванием немного выбивается из стиля.
7. Над полем, где можно попрактиковаться кодингу, стоит написать небольшое пояснение, что можно написать в нём что-то. Новичкам может быть непонятно. Или же, можно предоставить готовый код, попросить юзеров нажать на кнопку, и выйдет результат. Типа ого они уже кодят))
8. На четвертой странице отступы от краев блоков слева и справа можно сделать побольше.
9. Пояснить "Уровень: Начальный"

**Comment by indicozy** [comment]
можете отправить фото с указанием где стоило бы подправить дизайн?
